CREATE TABLE role(id_role INTEGER NOT NULL AUTO_INCREMENT, name VARCHAR(255) NOT NULL, PRIMARY KEY(id_role));
CREATE TABLE avatar(id_avatar INTEGER NOT NULL AUTO_INCREMENT, path VARCHAR(255) NOT NULL, PRIMARY KEY(id_avatar));
CREATE TABLE users (id_user INTEGER NOT NULL AUTO_INCREMENT, email VARCHAR(255) NOT NULL, password VARCHAR(255) NOT NULL,
 firstname VARCHAR(255) NOT NULL, lastname VARCHAR(255) NOT NULL, ROLE_id_role INTEGER NOT NULL, AVATAR_id_avatar INTEGER NOT NULL,
 PRIMARY KEY(id_user), FOREIGN KEY(ROLE_id_role) REFERENCES role(id_role), FOREIGN KEY(AVATAR_id_avatar) REFERENCES avatar(id_avatar));
CREATE TABLE calendar(id_calendar INTEGER NOT NULL AUTO_INCREMENT, name VARCHAR(255) NOT NULL, valid_until DATE, PRIMARY KEY(id_calendar));
CREATE TABLE eventTable(id_event INTEGER NOT NULL AUTO_INCREMENT, name VARCHAR(255) NOT NULL, description VARCHAR(255),
 start DATE NOT NULL, end DATE NOT NULL, CALENDAR_id_calendar INTEGER NOT NULL, PRIMARY KEY(id_event),
  FOREIGN KEY(CALENDAR_id_calendar) REFERENCES calendar(id_calendar));
CREATE TABLE category(id_category INTEGER NOT NULL AUTO_INCREMENT, name VARCHAR(255) NOT NULL, PRIMARY KEY(id_category));
CREATE TABLE events_categories(EVENT_id_event INTEGER NOT NULL, CATEGORY_id_category INTEGER NOT NULL,
 FOREIGN KEY(EVENT_id_event) REFERENCES eventTable(id_event), FOREIGN KEY(CATEGORY_id_category) REFERENCES category(id_category));
CREATE TABLE users_calendars(USER_id_user INTEGER NOT NULL, CALENDAR_id_calendar INTEGER NOT NULL,
 FOREIGN KEY(USER_id_user) REFERENCES users(id_user), FOREIGN KEY(CALENDAR_id_calendar) REFERENCES calendar(id_calendar));